[package]
name = "mocd"
version = "0.1.0"
edition = "2021"
authors = ["Guilherme Santos"]
license = "GPL3"


[profile.release]
debug = true

[dependencies]
petgraph = "0.6"
rand = "0.8"
rayon = "1.7"
rustc-hash = { version = "2.1", default-features = true }